### PR TITLE
fix(Player): :bug: Close properly audio streams

### LINKED ISSUE #32: Audio streams are kept open
### Describe the issue

The running audio streams are not properly closed.

### How to reproduce

1. Open the website
2. Go to the import page
3. Import a `.gp5` file
4. Start the track playing
5. Leave to another page

The audio track is still playing in the background

### How to fix

Make sure to properly close the audio stream when closing the sheet (leaving the page).

### PR DESCRIPTION
**Pull request by mlhoutel**
Handle the removal of alphaTab api on component destroy. Closes #32

### CODE REVIEW

File: src/components/TabSheet.vue [hunk 1]
```diff
@@ -104,6 +104,10 @@ export default Vue.extend({
   mounted() {
     this.loadApi()
   },
+  beforeDestroy() {
+    if (this.playing) this.play() // pause the currently playing track
+    this.api = undefined // clear object
```
Comment (reifocS) [inline src/components/TabSheet.vue:109]: destroy it properly with api.destroy()

Comment (mlhoutel) [reply src/components/TabSheet.vue:109]: Nice
